# Multiclass SVM 구현

In [45]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object

In [46]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [47]:
def standardization(train, test):
    scaler = StandardScaler()
    train = scaler.fit_transform(train)
    test = scaler.transform(test)
    return train, test

X_train, X_test = standardization(X_train, X_test)

In [48]:
X_train

array([[ 0.78522493,  0.32015325,  0.77221097,  1.04726529],
       [-0.26563371, -1.29989934,  0.0982814 , -0.11996537],
       [ 0.43493872,  0.78302542,  0.94069336,  1.43634218],
       [-0.84944407,  0.78302542, -1.24957775, -1.28719604],
       [-0.38239578, -1.7627715 ,  0.15444219,  0.13941922],
       [ 0.55170079, -0.374155  ,  1.05301496,  0.7878807 ],
       [ 0.31817664, -0.14271892,  0.65988937,  0.7878807 ],
       [ 0.20141457, -0.374155  ,  0.43524618,  0.39880381],
       [-1.66677857, -0.14271892, -1.36189934, -1.28719604],
       [-0.14887164, -0.60559109,  0.21060299,  0.13941922],
       [-0.14887164, -1.06846325, -0.12636179, -0.24965767],
       [ 0.31817664, -0.60559109,  0.15444219,  0.13941922],
       [ 0.66846286, -0.83702717,  0.88453256,  0.91757299],
       [ 0.0846525 , -0.14271892,  0.77221097,  0.7878807 ],
       [-0.49915786, -0.14271892,  0.43524618,  0.39880381],
       [-0.26563371, -0.60559109,  0.65988937,  1.04726529],
       [ 2.18636979,  1.70876975,  1.67078373,  1.30664988],
       [-0.49915786,  1.94020584, -1.13725615, -1.02781144],
       [-0.96620614,  1.0144615 , -1.36189934, -1.15750374],
       [ 1.60255943,  0.32015325,  1.27765815,  0.7878807 ],
       [-0.84944407,  1.70876975, -1.02493456, -1.02781144],
       [ 0.901987  , -0.14271892,  0.37908538,  0.26911151],
       [-1.19973028,  0.78302542, -1.02493456, -1.28719604],
       [-0.61591993,  1.47733367, -1.24957775, -1.28719604],
       [-0.49915786,  1.47733367, -1.24957775, -1.28719604],
       [-0.03210957, -0.83702717,  0.77221097,  0.91757299],
       [-1.31649236,  0.32015325, -1.19341695, -1.28719604],
       [ 1.25227322,  0.08871717,  0.94069336,  1.17695758],
       [-1.08296821,  0.08871717, -1.24957775, -1.41688833],
       [-1.08296821, -1.29989934,  0.43524618,  0.6581884 ],
       [ 0.43493872, -0.374155  ,  0.32292459,  0.13941922],
       [ 1.60255943,  1.24589758,  1.33381894,  1.69572677],
       [ 0.31817664, -0.374155  ,  0.54756778,  0.26911151],
       [ 1.83608357, -0.60559109,  1.33381894,  0.91757299],
       [-0.03210957, -0.83702717,  0.0982814 ,  0.00972692],
       [ 0.20141457, -1.99420759,  0.71605017,  0.39880381],
       [ 1.01874907,  0.08871717,  1.05301496,  1.56603447],
       [-0.84944407,  1.0144615 , -1.30573855, -1.15750374],
       [-0.14887164, -0.14271892,  0.26676379,  0.00972692],
       [-0.38239578, -1.53133542,  0.0421206 , -0.11996537],
       [ 0.55170079, -1.29989934,  0.71605017,  0.91757299],
       [ 1.48579736, -0.14271892,  1.22149735,  1.17695758],
       [-0.38239578, -1.06846325,  0.37908538,  0.00972692],
       [-0.96620614, -1.7627715 , -0.23868339, -0.24965767],
       [ 1.25227322,  0.08871717,  0.77221097,  1.43634218],
       [ 0.66846286, -0.60559109,  1.05301496,  1.17695758],
       [ 0.43493872, -1.99420759,  0.43524618,  0.39880381],
       [-0.14887164, -0.60559109,  0.43524618,  0.13941922],
       [-0.732682  , -0.83702717,  0.0982814 ,  0.26911151],
       [ 2.06960772, -0.14271892,  1.61462293,  1.17695758],
       [ 1.13551115, -0.60559109,  0.60372857,  0.26911151],
       [-0.84944407, -1.29989934, -0.40716578, -0.11996537],
       [-0.14887164, -1.29989934,  0.71605017,  1.04726529],
       [ 0.66846286, -0.374155  ,  0.32292459,  0.13941922],
       [ 1.01874907,  0.08871717,  0.37908538,  0.26911151],
       [-0.26563371, -0.83702717,  0.26676379,  0.13941922],
       [ 1.25227322,  0.08871717,  0.65988937,  0.39880381],
       [-0.84944407,  0.55158933, -1.13725615, -0.89811915],
       [-1.08296821, -0.14271892, -1.30573855, -1.28719604],
       [ 0.20141457, -0.83702717,  0.77221097,  0.52849611],
       [-1.08296821, -1.53133542, -0.23868339, -0.24965767],
       [-0.03210957,  2.17164192, -1.41806014, -1.28719604],
       [-0.96620614,  1.0144615 , -1.19341695, -0.76842685],
       [ 0.55170079, -0.83702717,  0.65988937,  0.7878807 ],
       [ 1.7193215 , -0.374155  ,  1.44614054,  0.7878807 ],
       [-0.732682  ,  2.403078  , -1.24957775, -1.41688833],
       [-0.14887164,  3.09738625, -1.24957775, -1.02781144],
       [ 1.13551115, -0.14271892,  0.99685416,  1.17695758],
       [-1.43325443,  0.08871717, -1.24957775, -1.28719604],
       [-0.03210957, -0.83702717,  0.21060299, -0.24965767],
       [ 1.01874907, -0.14271892,  0.82837177,  1.43634218],
       [ 1.36903529,  0.32015325,  0.54756778,  0.26911151],
       [-0.96620614,  0.32015325, -1.41806014, -1.28719604],
       [-0.96620614,  0.78302542, -1.24957775, -1.28719604],
       [ 0.55170079,  0.55158933,  1.27765815,  1.69572677],
       [ 2.18636979, -0.60559109,  1.67078373,  1.04726529],
       [ 0.0846525 , -0.14271892,  0.26676379,  0.39880381],
       [-1.31649236,  0.32015325, -1.36189934, -1.28719604],
       [ 0.66846286,  0.32015325,  0.88453256,  1.43634218],
       [-0.96620614,  0.78302542, -1.19341695, -1.02781144],
       [ 0.20141457,  0.78302542,  0.43524618,  0.52849611],
       [-1.19973028, -0.14271892, -1.30573855, -1.41688833],
       [ 1.01874907,  0.55158933,  1.10917575,  1.17695758],
       [ 0.78522493, -0.60559109,  0.49140698,  0.39880381],
       [-1.43325443,  1.24589758, -1.53038174, -1.28719604],
       [-0.03210957, -0.60559109,  0.77221097,  1.56603447],
       [-1.78354064, -0.14271892, -1.47422094, -1.41688833],
       [ 1.01874907, -1.29989934,  1.16533655,  0.7878807 ],
       [-1.08296821,  1.24589758, -1.30573855, -1.41688833],
       [-0.49915786,  1.94020584, -1.36189934, -1.02781144],
       [-1.43325443,  0.32015325, -1.30573855, -1.28719604],
       [-0.03210957, -0.83702717,  0.77221097,  0.91757299],
       [ 0.55170079, -0.60559109,  0.77221097,  0.39880381],
       [-0.96620614,  0.55158933, -1.30573855, -1.28719604],
       [ 2.41989393,  1.70876975,  1.50230134,  1.04726529],
       [-1.66677857,  0.32015325, -1.36189934, -1.28719604],
       [-1.19973028, -0.14271892, -1.30573855, -1.15750374],
       [ 1.01874907,  0.55158933,  1.10917575,  1.69572677],
       [-0.96620614, -2.45707976, -0.12636179, -0.24965767],
       [-0.732682  ,  1.0144615 , -1.24957775, -1.28719604],
       [ 2.18636979, -1.06846325,  1.78310533,  1.43634218],
       [ 1.13551115,  0.32015325,  1.22149735,  1.43634218],
       [-0.96620614, -0.14271892, -1.19341695, -1.28719604],
       [-0.84944407,  1.47733367, -1.24957775, -1.02781144],
       [ 2.18636979, -0.14271892,  1.33381894,  1.43634218],
       [-0.14887164,  1.70876975, -1.13725615, -1.15750374],
       [-0.26563371, -0.14271892,  0.43524618,  0.39880381],
       [-1.19973028,  0.08871717, -1.19341695, -1.28719604],
       [ 0.78522493, -0.14271892,  1.16533655,  1.30664988],
       [ 0.901987  , -0.374155  ,  0.49140698,  0.13941922],
       [-0.732682  ,  0.78302542, -1.30573855, -1.28719604],
       [-0.84944407,  1.70876975, -1.19341695, -1.28719604],
       [-1.43325443,  0.78302542, -1.30573855, -1.15750374],
       [-0.03210957, -1.06846325,  0.15444219,  0.00972692],
       [-1.08296821,  0.08871717, -1.24957775, -1.28719604],
       [-0.26563371, -0.374155  , -0.070201  ,  0.13941922],
       [ 0.31817664, -0.14271892,  0.49140698,  0.26911151],
       [-0.38239578, -1.53133542, -0.0140402 , -0.24965767],
       [ 0.66846286,  0.32015325,  0.43524618,  0.39880381],
       [-0.84944407,  1.0144615 , -1.30573855, -1.28719604]])

In [49]:
X_test

array([[-0.14887164, -0.374155  ,  0.26676379,  0.13941922],
       [ 0.31817664, -0.60559109,  0.54756778,  0.00972692],
       [ 0.31817664, -1.06846325,  1.05301496,  0.26911151],
       [-1.5500165 , -1.7627715 , -1.36189934, -1.15750374],
       [ 0.0846525 ,  0.32015325,  0.60372857,  0.7878807 ],
       [ 0.78522493, -0.14271892,  0.99685416,  0.7878807 ],
       [-0.84944407,  1.70876975, -1.24957775, -1.15750374],
       [ 0.20141457, -0.14271892,  0.60372857,  0.7878807 ],
       [-0.38239578,  2.63451409, -1.30573855, -1.28719604],
       [-0.38239578, -1.29989934,  0.15444219,  0.13941922],
       [ 0.66846286,  0.08871717,  0.99685416,  0.7878807 ],
       [-0.38239578,  1.0144615 , -1.36189934, -1.28719604],
       [-0.49915786,  0.78302542, -1.13725615, -1.28719604],
       [ 0.43493872, -0.60559109,  0.60372857,  0.7878807 ],
       [ 0.55170079, -1.7627715 ,  0.37908538,  0.13941922],
       [ 0.55170079,  0.55158933,  0.54756778,  0.52849611],
       [-1.19973028,  0.78302542, -1.19341695, -1.28719604],
       [ 0.20141457, -1.99420759,  0.15444219, -0.24965767],
       [ 0.55170079, -1.29989934,  0.65988937,  0.39880381],
       [ 1.25227322,  0.32015325,  1.10917575,  1.43634218],
       [-1.66677857, -0.374155  , -1.30573855, -1.28719604],
       [ 0.78522493, -0.14271892,  0.82837177,  1.04726529],
       [ 1.01874907, -0.14271892,  0.71605017,  0.6581884 ],
       [ 1.01874907,  0.08871717,  0.54756778,  0.39880381],
       [ 1.60255943, -0.14271892,  1.16533655,  0.52849611],
       [-0.96620614,  1.24589758, -1.30573855, -1.28719604],
       [-0.49915786,  0.78302542, -1.24957775, -1.02781144],
       [ 0.55170079,  0.78302542,  1.05301496,  1.56603447],
       [ 0.66846286, -0.60559109,  1.05301496,  1.30664988],
       [-0.26563371, -0.14271892,  0.21060299,  0.13941922]])

In [50]:
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.fit_transform(X_test)

One vs Rest

In [56]:
svm_set = SVC(kernel='rbf', C=5, gamma=5)
svm_ver = SVC(kernel='rbf', C=5, gamma=5)
svm_vir = SVC(kernel='rbf', C=5, gamma=5)

In [57]:
y_train = pd.get_dummies(y_train)
y_train

     setosa  versicolor  virginica
110       0           0          1
69        0           1          0
148       0           0          1
39        1           0          0
53        0           1          0
..      ...         ...        ...
64        0           1          0
91        0           1          0
81        0           1          0
51        0           1          0
0         1           0          0

[120 rows x 3 columns]

In [58]:
svm_set.fit(X_train, y_train.iloc[:,0])#setsosa 인지 아닌지 구분
svm_ver.fit(X_train, y_train.iloc[:,1])#versicolor인지 아닌지 구분
svm_vir.fit(X_train, y_train.iloc[:,2])#virginica인지 아닌지 구분

y_preds_set=svm_set.predict(X_test)
y_preds_ver=svm_ver.predict(X_test)
y_preds_vir=svm_vir.predict(X_test)

In [63]:
print(y_preds_set)
print(y_preds_ver)
print(y_preds_vir)

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0 1 1 0 0 0]
[1 1 1 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 1]
[0 0 0 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 0 0 1 1 0]

Decision_function의 활용

Xndarray of shape (n_samples, n_classes * (n_classes-1) / 2)
Returns the decision function of the sample for each class in the model. 
If decision_function_shape=’ovr’, the shape is (n_samples, n_classes).즉 n개의 데이터가 one or rest의 판별함수값을 계산한다.

동점자 처리

In [66]:
tied_idx=[]
for i in range(X_test.shape[0]):
    if y_preds_set[i] + y_preds_ver[i] + y_preds_vir[i] !=1: #답이 나오지 않은 경우에 관하여
        tied_idx.append(i)

In [67]:
tied_idx #답이 나오지 않은 경우 발생

[3, 4, 17, 18, 20]

In [86]:
decs=[]
decs.append(svm_set.decision_function(X_test))
decs.append(svm_ver.decision_function(X_test))
decs.append(svm_vir.decision_function(X_test))
decs

[array([-1.09479249, -0.88441888, -0.67698027, -0.50193576, -0.71739227,
        -0.86457961,  0.24859407, -0.93887282,  0.35131072, -0.99900635,
        -0.86332953,  0.15305939,  0.70839528, -0.92872488, -0.64175307,
        -0.92713794,  0.43964422, -0.57555901, -0.72819946, -0.81140457,
        -0.07475588, -0.96431996, -0.82539457, -1.03941474, -0.6857359 ,
         0.91252255,  0.89413648, -0.98621503, -0.9181254 , -0.9108343 ]),
 array([ 1.24757843,  0.77775283,  0.18148431, -0.37104797, -0.16514643,
        -0.70005354, -0.68543786, -0.73808682, -0.72822984,  0.97380194,
        -0.72380382, -0.64541512, -0.87804291, -0.7406918 ,  0.23202216,
         0.74726978, -0.7654804 , -0.1560107 , -0.18055305, -0.76042806,
        -0.54996444, -0.95250956,  0.26749494,  1.1409139 , -0.56777845,
        -0.96359278, -0.95592498, -0.98341218, -0.8622402 ,  0.76207132]),
 array([-1.16156543, -0.91359823, -0.50486889, -0.13015203, -0.11388351,
         0.50457725, -0.56467952,  0.69917779, -0.62457794, -0.97060768,
         0.55591468, -0.5093546 , -0.83116414,  0.66987982, -0.59241143,
        -0.81670683, -0.67518055, -0.27120282, -0.08514657,  0.57120342,
        -0.37754287,  0.89924163, -0.44978617, -1.09127257,  0.25089537,
        -0.94934715, -0.93872108,  0.96981166,  0.80626086, -0.84536832])]

In [87]:
def decision_make(models, X_test):
  decisions=[]
  for model in models:
    decisions.append(model.decision_function(X_test))
  
  for _ in decisions:
    fin = np.argmax(decisions, axis=0)

  return pd.DataFrame(fin, columns=['final_decision']).replace({0:'setosa', 1:'versicolor', 2:'virginica'})

models = [svm_set, svm_ver, svm_vir]

decision_make(models, X_test)

   final_decision
0      versicolor
1      versicolor
2      versicolor
3       virginica
4       virginica
5       virginica
6          setosa
7       virginica
8          setosa
9      versicolor
10      virginica
11         setosa
12         setosa
13      virginica
14     versicolor
15     versicolor
16         setosa
17     versicolor
18      virginica
19      virginica
20         setosa
21      virginica
22     versicolor
23     versicolor
24      virginica
25         setosa
26         setosa
27      virginica
28      virginica
29     versicolor

In [88]:
accuracy_score(y_test,decision_make(models, X_test))

0.8666666666666667

In [89]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)
X_train, X_test = standardization(X_train, X_test)

svm = SVC(kernel ='rbf', C = 5, gamma = 5)
svm.fit(X_train, y_train)
y_pred = pd.DataFrame({'sklearn':svm.predict(X_test).tolist()})
y_pred

       sklearn
0   versicolor
1   versicolor
2   versicolor
3    virginica
4    virginica
5    virginica
6       setosa
7    virginica
8       setosa
9   versicolor
10   virginica
11      setosa
12      setosa
13   virginica
14  versicolor
15  versicolor
16      setosa
17  versicolor
18   virginica
19   virginica
20      setosa
21   virginica
22  versicolor
23  versicolor
24   virginica
25      setosa
26      setosa
27   virginica
28   virginica
29  versicolor

In [90]:
accuracy_score(y_test,y_pred)

0.8666666666666667

In [91]:
compares=pd.concat([y_pred, decision_make(models, X_test)],axis=1)
compares

       sklearn final_decision
0   versicolor     versicolor
1   versicolor     versicolor
2   versicolor     versicolor
3    virginica      virginica
4    virginica      virginica
5    virginica      virginica
6       setosa         setosa
7    virginica      virginica
8       setosa         setosa
9   versicolor     versicolor
10   virginica      virginica
11      setosa         setosa
12      setosa         setosa
13   virginica      virginica
14  versicolor     versicolor
15  versicolor     versicolor
16      setosa         setosa
17  versicolor     versicolor
18   virginica      virginica
19   virginica      virginica
20      setosa         setosa
21   virginica      virginica
22  versicolor     versicolor
23  versicolor     versicolor
24   virginica      virginica
25      setosa         setosa
26      setosa         setosa
27   virginica      virginica
28   virginica      virginica
29  versicolor     versicolor

MultiClassSVM 클래스로도 구현 시도해보기